DROP DATABASE IF EXISTS dbms;
CREATE DATABASE dbms;
USE dbms;
DROP TABLE IF EXISTS phptable;
CREATE TABLE phptable (
	id int PRIMARY KEY AUTO_INCREMENT,
	NAME varchar(255),
	LASTNAME varchar(255),
    BIRTHDATE date,
	USERNAME varchar(255),
	PASSWORD varchar(255),
	REGISTRATION_DATE DATETIME NOT NULL
);